# Generated by Django 3.0 on 2019-12-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='distance',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_closed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tacoboutit_item_review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='url',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
