# Generated by Django 3.0 on 2019-12-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20191218_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
