# Generated by Django 3.0.1 on 2020-01-06 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_taco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taco',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tacos', to='myapi.Restaurant'),
        ),
    ]
