# Generated by Django 3.0 on 2019-12-31 17:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_taco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taco',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tacos', to='myapi.Restaurant'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('review', models.TextField(max_length=900)),
                ('taco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapi.Taco')),
            ],
        ),
    ]
