# Generated by Django 3.0 on 2020-01-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_auto_20191231_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
