# Generated by Django 3.0 on 2020-01-07 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_auto_20200106_2212'),
        ('myapi', '0013_delete_hero'),
    ]

    operations = [
    ]
